import { router } from "expo-router";
import { useState, type ReactNode } from "react";
import { Image, Pressable, View } from "react-native";
import { useSessao } from "@/features/auth/sessao";
import { Screen } from "@/ui/componentes/Screen";
import { TextoPainel as Texto, useTipografiaPainel } from "./tipografia";
import { Icone } from "@/ui/componentes/Icone";
import { ButtonPainel as Button } from "./tipografia";
import { Banner } from "@/ui/componentes/Banner";
import { SIMBOLO } from "@/ui/stickers";
import { useTema } from "@/ui/tema";
import { usePainel } from "./provider";
import { Acao, Folha, RecursoDados } from "./base";
import { PERFIS, TITULOS, nomeMes, mesesAnteriores, mesAtual, type Widget } from "./catalogo";
export function TelaPainel({ titulo, children }: { titulo: string; children: ReactNode }) {
 const { ampliado } = useTipografiaPainel();
 const p = usePainel(); const sessao = useSessao(); const { cores } = useTema();
 const [folha, setFolha] = useState<"perfil" | "mes" | "organizar" | "conta" | null>(null);
 const [erroSaida, setErroSaida] = useState<string | null>(null); const [saindo, setSaindo] = useState(false);
 const nome = p.usuario.display_name?.trim() || p.usuario.email?.split("@")[0] || "Você";
 const label = PERFIS.find((x) => x.id === p.perfil)!.label;
 const mover = (id: Widget, dir: number) => { const ids = [...p.layout], i = ids.indexOf(id), j = i + dir; if (j < 0 || j >= ids.length) return; const atual = ids[i]!, outro = ids[j]!; ids[i] = outro; ids[j] = atual; p.organizar(ids); };
 const sair = async () => { setSaindo(true); setErroSaida(null); if (!(await sessao.sair())) { setSaindo(false); setErroSaida("Não conseguimos sair. Tente de novo."); } };
 return <><Screen onAtualizar={p.atualizar} atualizando={p.atualizando}><View style={{ gap: 20, paddingTop: 12, paddingBottom: 24 }}>
 <View style={{ flexDirection: "row", alignItems: "center", gap: 12 }}><Pressable accessibilityRole="button" accessibilityLabel="PigBank, abrir Resumo" onPress={() => router.navigate("/resumo")} style={{ flex: 1, minWidth: 0, minHeight: 44, justifyContent: "center" }}><View style={{ flexDirection: "row", gap: 5, alignItems: "center" }}><Image source={SIMBOLO} style={{ width: 28, height: 28 }} accessibilityIgnoresInvertColors /><Texto variante="secao" style={{ letterSpacing: -1, fontSize: 26, flexShrink: 1 }}>PigBank</Texto></View></Pressable><Pressable testID="painel-privacidade" accessibilityRole="button" accessibilityLabel={p.oculto ? "Mostrar valores" : "Ocultar valores"} onPress={p.alternarPrivacidade} style={{ width: 44, height: 44, flexShrink: 0, alignItems: "center", justifyContent: "center" }}><Icone nome={p.oculto ? "EyeSlash" : "Eye"} /></Pressable><Pressable testID="painel-conta" accessibilityRole="button" accessibilityLabel="Abrir minha conta" onPress={() => setFolha("conta")} style={{ width: 44, height: 44, flexShrink: 0, borderRadius: 22, backgroundColor: cores.surfaceRaised, alignItems: "center", justifyContent: "center" }}><Texto variante="rotulo">{nome.slice(0, 1).toUpperCase()}</Texto></Pressable></View>
 <View style={{ gap: 8 }}>{titulo === "Resumo" && <Texto variante="rotulo" tom="inkMuted">Bom dia, {nome}</Texto>}<View style={{ flexDirection: ampliado ? "column" : "row", alignItems: ampliado ? "flex-start" : "center", gap: 12 }}><Texto variante="titulo" accessibilityRole="header" style={{ flex: ampliado ? undefined : 1, flexShrink: 1, minWidth: 0 }}>{titulo === "Resumo" ? `Resumo de ${nomeMes(p.mes).split(" de ")[0]}` : titulo}</Texto><Acao rotulo={nomeMes(p.mes).slice(0, 3)} icone="CaretDown" onPress={() => setFolha("mes")} /></View>{titulo === "Resumo" && <Texto variante="rotulo" tom="inkMuted">O mês inteiro num lugar.</Texto>}</View>
 {titulo === "Resumo" && <View style={{ flexDirection: "row", justifyContent: "space-between", flexWrap: "wrap", gap: 12 }}><Acao rotulo={label} icone="CaretDown" onPress={() => setFolha("perfil")} desativado={p.salvandoPerfil} /><Acao rotulo="Organizar" icone="SlidersHorizontal" onPress={() => setFolha("organizar")} /></View>}
 {p.pendente && <Button rotulo="Retomar conexão" variante="secondary" onPress={() => router.push("/open-finance-volta")} />}{p.aviso && <Banner tom="warning" mensagem={p.aviso} />}
 {titulo === "Resumo" && <Pressable accessibilityRole="button" accessibilityLabel="Conversar com o Piggy" onPress={() => router.navigate("/piggy")} style={{ padding: 12, borderRadius: 12, backgroundColor: cores.brandSoft, flexDirection: "row", alignItems: "center", gap: 12 }}><Image source={SIMBOLO} style={{ width: 44, height: 44 }} accessibilityIgnoresInvertColors /><View style={{ flex: 1, gap: 3 }}><Texto variante="rotulo">Seu dinheiro conta uma história.</Texto><Texto variante="legenda" tom="inkMuted">Pergunte ao Piggy o que mudou no mês.</Texto></View><Icone nome="CaretRight" tamanho={20} /></Pressable>}{children}</View></Screen>
 <Folha titulo="Seu perfil" aberta={folha === "perfil" || p.escolhendo} fechar={() => { if (p.escolhendo) void p.mudarPerfil("padrao"); setFolha(null); }}><Texto tom="inkMuted">Escolha o que você quer acompanhar primeiro. Cada perfil tem sua própria organização.</Texto>{PERFIS.map((perfil) => <Button key={perfil.id} rotulo={perfil.label + (p.perfil === perfil.id ? " · selecionado" : "")} variante="secondary" desativado={p.salvandoPerfil} onPress={() => { void p.mudarPerfil(perfil.id); setFolha(null); }} />)}</Folha>
 <Folha titulo="Escolher mês" aberta={folha === "mes"} fechar={() => setFolha(null)}>{mesesAnteriores(mesAtual()).map((mes) => <Button key={mes} rotulo={nomeMes(mes) + (p.mes === mes ? " · selecionado" : "")} variante="secondary" onPress={() => { p.mudarMes(mes); setFolha(null); }} />)}<Texto variante="legenda" tom="inkMuted">A disponibilidade do histórico depende do seu acesso.</Texto></Folha>
 <Folha titulo="Organizar painel" aberta={folha === "organizar"} fechar={() => setFolha(null)}><Texto tom="inkMuted">Perfil: {label}</Texto>{!p.layout.length && <Texto>Seu painel está vazio. Adicione os blocos abaixo.</Texto>}{p.layout.map((id, i) => <View key={id} style={{ gap: 4 }}><Texto variante="rotulo">{TITULOS[id]}</Texto><View style={{ flexDirection: "row", justifyContent: "space-between", flexWrap: "wrap" }}><Acao rotulo={`Subir ${TITULOS[id]}`} icone="ArrowUp" somenteIcone desativado={i === 0} onPress={() => mover(id, -1)} /><Acao rotulo={`Descer ${TITULOS[id]}`} icone="ArrowDown" somenteIcone desativado={i === p.layout.length - 1} onPress={() => mover(id, 1)} /><Acao rotulo={`Esconder ${TITULOS[id]}`} icone="Minus" somenteIcone onPress={() => p.organizar(p.layout.filter((v) => v !== id))} /></View></View>)}<Texto variante="secao">Adicionar blocos</Texto>{(Object.keys(TITULOS) as Widget[]).filter((id) => !p.layout.includes(id)).map((id) => <Acao key={id} rotulo={`Adicionar ${TITULOS[id]}`} icone="Plus" onPress={() => p.organizar([...p.layout, id])} />)}<Button rotulo="Restaurar padrão deste perfil" variante="secondary" onPress={() => p.organizar(null)} /><Button rotulo="Pronto" onPress={() => setFolha(null)} /></Folha>
 <Folha titulo="Minha conta" aberta={folha === "conta"} fechar={() => setFolha(null)}><Texto variante="secao">{nome}</Texto><RecursoDados nome="plano">{(d) => <Texto tom="inkMuted">Plano {d.plan_tier === "free" ? "Grátis" : d.plan_tier === "essencial" ? "Essencial" : d.plan_tier === "plus" ? "Plus" : "Pro"} · acesso confirmado no servidor.</Texto>}</RecursoDados>{([ ["Bancos conectados", "/conexoes"], ["Configurações", "/configuracoes"], ["Segurança", "/seguranca"] ] as const).map(([rotulo, destino]) => <Button key={destino} rotulo={rotulo} variante="secondary" onPress={() => { setFolha(null); router.push(destino); }} />)}{erroSaida && <Banner tom="danger" mensagem={erroSaida} />}<Button rotulo="Sair" variante="secondary" carregando={saindo} onPress={() => void sair()} /></Folha></>;
}
