import { useEffect, useRef, useState, type ReactNode } from "react";
import { View } from "react-native";
import { TextoPainel as Texto, useTipografiaPainel } from "./tipografia";
import { ProgressBar } from "@/ui/componentes/ProgressBar";
import { marcarAssinatura } from "@/services/painel";
import { dataPtBr, nomeLegivel, nomeMes } from "./catalogo";
import { usePainel, mensagemRecurso } from "./provider";
import { RecursoDados, Valor, Linha, Acao, Vazio } from "./base";
export function Faturas() { const p = usePainel(); return <RecursoDados nome="cartoes">{(d) => <View style={{ gap: 12 }}>{!d.cards.length && <Vazio texto="Nenhum cartão cadastrado." />}{d.cards.map((c) => <View key={c.id} style={{ gap: 6 }}><Texto variante="secao">{nomeLegivel(c.name)}{c.last4 && !p.oculto ? ` · ${c.last4}` : ""}</Texto><Valor valor={c.open_bill.due_amount} destaque /><Texto variante="legenda" tom="inkMuted">Vencimento dia {c.due_day} · fechamento dia {c.closing_day}</Texto><Linha titulo="Limite" valor={c.credit_limit} /><Linha titulo="Crédito utilizado" valor={c.credit_used} />{!p.oculto && c.credit_limit !== null && c.credit_limit > 0 && <ProgressBar valor={c.credit_used / c.credit_limit} />}<Linha titulo="Já pago nesta fatura" valor={c.open_bill.paid_amount} /></View>)}</View>}</RecursoDados>; }
export function Parcelas() { const p = usePainel(); return <RecursoDados nome="parcelas">{(d) => <View style={{ gap: 12 }}>{!d.installments.length && <Vazio texto="Não há parcelamentos registrados." />}{d.installments.map((g) => <View key={g.group_id} style={{ gap: 4 }}><Linha titulo={g.name} detalhe={nomeLegivel(g.card_name)} />{g.parcelas.map((parcela) => <Linha key={parcela.tx_id} titulo={`Parcela ${parcela.installment_no} de ${g.installments_total}`} valor={parcela.valor} detalhe={`${dataPtBr(parcela.due_date)} · ${parcela.is_paid ? "paga" : parcela.is_next ? "próxima" : "pendente"}`} />)}{!p.oculto && <ProgressBar valor={g.parcelas.filter((x) => x.is_paid).length / Math.max(1, g.parcelas.length)} />}</View>)}</View>}</RecursoDados>; }
export function Renda() { return <RecursoDados nome="renda">{(d) => <View style={{ gap: 8 }}>{!d.evolution.length && <Vazio texto="Ainda não há histórico de renda disponível." />}{d.evolution.map((m) => <View key={m.month}><Linha titulo={nomeMes(m.month)} valor={m.income} /><Linha titulo="Saídas" valor={m.expense} /></View>)}</View>}</RecursoDados>; }
export function Assinaturas() {
 const p = usePainel(); const { ampliado } = useTipografiaPainel(); const [ocupado, setOcupado] = useState<string | null>(null); const voo = useRef<symbol | null>(null); const dono = useRef(p.usuario.user_id); dono.current = p.usuario.user_id; const [erro, setErro] = useState<string | null>(null);
 useEffect(() => { voo.current = null; setOcupado(null); setErro(null); }, [p.usuario.user_id]);
 const marcar = async (chave: string, status: "assinatura" | "ignorar" | "nenhuma") => { if (voo.current) return; const token = Symbol(), uid = p.usuario.user_id; voo.current = token; setOcupado(chave); setErro(null); const op = p.operacao(); try { await marcarAssinatura(chave, status, op.controlador); if (op.atual()) p.atualizar(); } catch (e) { if (op.atual()) { setErro(mensagemRecurso(e)); p.falhou(e); } } finally { if (voo.current === token && dono.current === uid) { setOcupado(null); voo.current = null; } } };
 // Ação à direita da linha; em fonte ampliada, embaixo. Em coluna o `flex: 1` zeraria a altura, daí o `stretch`.
 const item = (chave: string, linha: ReactNode, acao: ReactNode) => <View key={chave} style={{ flexDirection: ampliado ? "column" : "row", alignItems: ampliado ? "flex-start" : "center", gap: 8 }}><View style={ampliado ? { alignSelf: "stretch" } : { flex: 1, minWidth: 0 }}>{linha}</View>{acao}</View>;
 return <RecursoDados nome="assinaturas">{(d) => <View style={{ gap: 8 }}><Linha titulo="Mensal" valor={d.total_mensal} /><Linha titulo="Anual estimado" valor={d.total_anual} />{erro && <Texto tom="warning">{erro}</Texto>}{!d.servicos.length && <Vazio texto="Nenhuma assinatura detectada." />}{d.servicos.map((a) => item(a.chave, <Linha titulo={a.nome} valor={a.valor} detalhe={`${dataPtBr(a.proxima)} · ${nomeLegivel(a.meio.nome)}${a.meio.final && !p.oculto ? ` ••${a.meio.final}` : ""} · ${a.status.replaceAll("_", " ")}`} />, <Acao rotulo={ocupado === a.chave ? "Salvando…" : `Ignorar ${a.nome}`} texto={ocupado === a.chave ? "Salvando…" : "Ignorar"} compacta desativado={!!ocupado} onPress={() => void marcar(a.chave, "ignorar")} />))}{d.outras.map((a) => item(a.chave, <Linha titulo={a.nome} valor={a.valor} detalhe="Outra recorrência" />, <Acao rotulo={`Marcar ${a.nome} como assinatura`} texto="É assinatura" compacta desativado={!!ocupado} onPress={() => void marcar(a.chave, "assinatura")} />))}{d.ignoradas.map((a) => item(a.chave, <Linha titulo={a.nome} detalhe="Ignorada" />, <Acao rotulo={`Reconsiderar ${a.nome}`} texto="Reconsiderar" compacta desativado={!!ocupado} onPress={() => void marcar(a.chave, "nenhuma")} />))}</View>}</RecursoDados>;
}
export function Notou() { const p = usePainel(); return <RecursoDados nome="insights">{(d) => <View style={{ gap: 8 }}>{!d.insights.length && <Vazio texto="O Piggy ainda não encontrou um destaque para você." />}{d.insights.map((i) => <View key={i.key} style={{ gap: 6 }}><Texto variante="rotulo">{p.oculto ? "Destaque oculto" : i.title}</Texto><Texto variante="rotulo" tom="inkMuted">{p.oculto ? "Mostre os valores para ler este destaque." : i.message}</Texto></View>)}</View>}</RecursoDados>; }
