import { View } from "react-native";
import { ChipPainel as Chip, TextoPainel as Texto } from "./tipografia";
import { dataPtBr, nomeLegivel } from "./catalogo";
import { usePainel } from "./provider";
import { RecursoDados, Valor, Curva, Linha, Vazio, Filtros } from "./base";
export function Previsao() { const p = usePainel(); return <RecursoDados nome="previsao">{(d) => <View style={{ gap: 8 }}><Filtros>{d.dias_permitidos.map((dias) => <Chip key={dias} rotulo={`${dias} dias`} selecionado={d.dias === dias} onPress={() => p.mudarDias(dias)} />)}</Filtros><Texto variante="legenda" tom="inkMuted">A partir de hoje, {dataPtBr(d.hoje).slice(0, 5)}</Texto><Valor valor={d.marcos.find((m) => m.dias === d.dias)?.saldo ?? null} destaque />{d.estado === "indisponivel" && <Texto variante="rotulo" tom="warning">Previsão indisponível</Texto>}{d.trajetoria ? <Curva valores={d.trajetoria.map((t) => t.saldo)} /> : <Vazio texto="Trajetória indisponível no seu plano." />}{d.marcos.map((m) => <Linha key={m.dias} titulo={`${m.dias} dias · ${dataPtBr(m.data)}`} valor={m.saldo} />)}{d.pior_dia && <Linha titulo={`Menor saldo previsto · ${dataPtBr(d.pior_dia.data)}`} valor={d.pior_dia.saldo} />}</View>}</RecursoDados>; }
export function Compromissos() { return <RecursoDados nome="previsao">{(d) => {
 const todas = (d.compromissos ?? []).flatMap((g) => g.ocorrencias), nome = (o: (typeof todas)[number]) => o.tipo === "fatura_cartao" ? nomeLegivel(o.nome) : o.nome;
 // Vencida ou sem data e SEM valor some: não há o que pagar nem conferir nela. Vencida com valor vem antes, sem data no fim.
 const porData = (a: (typeof todas)[number], b: (typeof todas)[number]) => a.data!.localeCompare(b.data!);
 const linhas = [...todas.filter((o) => o.data !== null && o.data < d.hoje && o.valor !== null).sort(porData).map((o) => [o, `venceu ${dataPtBr(o.data).slice(0, 5)}`] as const), ...todas.filter((o) => o.data !== null && o.data >= d.hoje).sort(porData).map((o) => [o, dataPtBr(o.data)] as const), ...todas.filter((o) => o.data === null && o.valor !== null).map((o) => [o, "sem data"] as const)];
 return <View style={{ gap: 4 }}>{d.compromissos === null ? <Vazio texto="Compromissos indisponíveis no seu plano." /> : !linhas.length ? <Vazio texto="Nenhum compromisso conhecido nesta janela." /> : linhas.map(([o, quando]) => <Linha key={o.chave + o.ciclo} titulo={nome(o)} valor={o.valor} detalhe={[quando, o.qualidade_valor === "estimado" && "valor estimado", o.qualidade_data === "presumida" && "data presumida", o.realizacao === "a_conferir" ? "a conferir" : o.realizacao === "realizada" ? (o.direcao === "entrada" ? "recebido" : "pago") : null, !o.incluida_no_calculo && "fora do cálculo"].filter(Boolean).join(" · ")} />)}</View>;
}}</RecursoDados>; }
