import { View } from "react-native";
import { TextoPainel as Texto } from "./tipografia";
import { dataPtBr, nomeLegivel } from "./catalogo";
import { usePainel } from "./provider";
import { RecursoDados, Valor, Curva, Acao, Linha, Vazio } from "./base";
export function Previsao() { const p = usePainel(); return <RecursoDados nome="previsao">{(d) => <View style={{ gap: 12 }}><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 16 }}>{d.dias_permitidos.map((dias) => <Acao key={dias} rotulo={`${dias} dias${d.dias === dias ? " · selecionado" : ""}`} onPress={() => p.mudarDias(dias)} />)}</View><Texto variante="legenda" tom="inkMuted">Projeção a partir de {dataPtBr(d.hoje)}, considerando compromissos conhecidos.</Texto>{p.mes !== d.hoje.slice(0, 7) && <Texto variante="legenda" tom="warning">A previsão se refere a hoje, mesmo com outro mês selecionado.</Texto>}<Valor valor={d.marcos.find((m) => m.dias === d.dias)?.saldo ?? null} destaque /><Texto variante="rotulo" tom={d.estado === "condicional" ? "inkMuted" : "warning"}>{d.estado === "condicional" ? "Saldo condicional" : d.estado === "a_conferir" ? "Há compromissos a conferir" : "Previsão indisponível"}</Texto>{d.trajetoria ? <Curva valores={d.trajetoria.map((t) => t.saldo)} /> : <Vazio texto="Seu acesso mostra marcos; a trajetória diária não está disponível." />}{d.marcos.map((m) => <Linha key={m.dias} titulo={`${m.dias} dias · ${dataPtBr(m.data)}`} valor={m.saldo} />)}{d.pior_dia && <Linha titulo={`Menor saldo previsto · ${dataPtBr(d.pior_dia.data)}`} valor={d.pior_dia.saldo} />}{d.premissas.map((m, i) => <Texto key={i} variante="legenda" tom="inkMuted">{m}</Texto>)}{!d.cobertura.inclui_estimativa_variavel && <Texto variante="legenda" tom="warning">Gastos variáveis não entram nesta projeção.</Texto>}{[...new Set(d.motivos.map((m) => m.direcao_do_erro === "so_melhora" ? "O saldo pode ser maior quando as informações forem confirmadas." : m.direcao_do_erro === "so_piora" ? "O saldo pode ser menor quando as informações forem confirmadas." : "O saldo pode aumentar ou diminuir após a conferência."))].map((m) => <Texto key={m} variante="legenda" tom="warning">{m}</Texto>)}</View>}</RecursoDados>; }
export function Compromissos() { return <RecursoDados nome="previsao">{(d) => {
 const todas = (d.compromissos ?? []).flatMap((g) => g.ocorrencias), nome = (o: (typeof todas)[number]) => o.tipo === "fatura_cartao" ? nomeLegivel(o.nome) : o.nome;
 const futuras = todas.filter((o) => o.data !== null && o.data >= d.hoje).sort((a, b) => a.data!.localeCompare(b.data!)), anteriores = todas.filter((o) => !futuras.includes(o));
 return <View style={{ gap: 8 }}><Texto variante="legenda" tom="inkMuted">Próximos {d.dias} dias a partir de {dataPtBr(d.hoje)}.</Texto>{d.compromissos === null ? <Vazio texto="Detalhes de compromissos não disponíveis no seu acesso." /> : !futuras.length ? <Vazio texto="Nenhum compromisso conhecido nesta janela." /> : futuras.map((o) => <Linha key={o.chave + o.ciclo} titulo={nome(o)} valor={o.valor} detalhe={[dataPtBr(o.data), o.qualidade_valor === "estimado" && "valor estimado", o.qualidade_data === "presumida" && "data presumida", o.realizacao === "a_conferir" ? "a conferir" : o.realizacao === "realizada" ? (o.direcao === "entrada" ? "recebido" : "pago") : null, !o.incluida_no_calculo && "fora do cálculo"].filter(Boolean).join(" · ")} />)}{anteriores.length > 0 && <Linha titulo={`${anteriores.every((o) => o.tipo === "fatura_cartao") ? "Faturas" : "Compromissos"} a conferir (${anteriores.length})`} detalhe={[...new Set(anteriores.map(nome))].join(", ")} />}</View>;
}}</RecursoDados>; }
