import { useNavegacaoPainel } from "./navegacao";
import { useState } from "react";
import { View } from "react-native";
import { TextoPainel as Texto, useTipografiaPainel } from "./tipografia";
import { ProgressBar } from "@/ui/componentes/ProgressBar";
import { dataPtBr, nomeCategoria, nomeMes } from "./catalogo";
import { usePainel } from "./provider";
import { RecursoDados, Anel, Linha, Avisos, Acao, Vazio, Valor } from "./base";
import { somarCentavos, percentualEmCentavos } from "./decimal";
export function Categorias() { const { navegar } = useNavegacaoPainel(); const p = usePainel(); const catalogo = p.dados.categorias?.fase === "pronto" ? p.dados.categorias.dado.categorias : undefined; return <RecursoDados nome="detalhes">{(d) => <View style={{ gap: 12 }}>{!d.categorias.length ? <Vazio texto="Nenhum gasto em reais registrado neste período." /> : <><View style={{ flexDirection: "row", gap: 20, alignItems: "center" }}><Anel partes={d.categorias.map((c) => c.valor)} /><View style={{ flex: 1, gap: 4 }}><Texto variante="legenda" tom="inkMuted">Gastos em reais</Texto><Valor valor={somarCentavos(d.categorias.map((c) => c.valor))} /></View></View>{d.categorias.map((c, i) => <View key={c.categoria ?? i} style={{ gap: 4 }}><Linha titulo={nomeCategoria(c.categoria, catalogo)} valor={c.valor} onPress={() => navegar({ pathname: "/extrato", params: { categoria: c.categoria ?? "" } })} />{!p.oculto && <ProgressBar valor={c.valor / Math.max(1, somarCentavos(d.categorias.map((x) => x.valor)))} />}</View>)}</>}<Avisos motivos={d.motivos} /><Texto variante="legenda" tom="inkMuted">Mês da fatura para cartão; outras moedas e transferências internas fora desta distribuição.</Texto></View>}</RecursoDados>; }
export function Calendario() { const { navegar } = useNavegacaoPainel(); const { ampliado } = useTipografiaPainel(); return <RecursoDados nome="detalhes">{(d) => <View style={{ gap: 8 }}><Texto variante="legenda" tom="inkMuted">Dia do lançamento ou compra, na fatura deste mês.</Texto>{d.dias.length ? <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{d.dias.map((dia) => <View key={dia.dia} testID={`calendario-dia-${dia.dia}`} style={{ width: ampliado ? "47%" : "30%", paddingVertical: 4 }}><Acao rotulo={dataPtBr(dia.dia)} onPress={() => navegar({ pathname: "/extrato", params: { dia: dia.dia } })} /><Texto variante="legenda" tom="inkMuted">Entrou</Texto><Valor valor={dia.entrou} tipo="entrada" /><Texto variante="legenda" tom="inkMuted">Saiu</Texto><Valor valor={dia.saiu} tipo="saida" /></View>)}</View> : <Vazio texto="Ainda não há movimentos neste período." />}<Avisos motivos={d.motivos} /></View>}</RecursoDados>; }
export function Simulador() {
 const { ampliado } = useTipografiaPainel();
 const p = usePainel(); const catalogo = p.dados.categorias?.fase === "pronto" ? p.dados.categorias.dado.categorias : undefined; const [cortes, setCortes] = useState<Record<string, number>>({});
 return <RecursoDados nome="detalhes">{(d) => { const economias = d.categorias.map((c) => percentualEmCentavos(c.valor, cortes[c.categoria ?? ""] ?? 0)); return <View style={{ gap: 14 }}><Texto variante="rotulo" tom="inkMuted">Economia potencial sobre os gastos observados em {nomeMes(d.mes)}.</Texto>{d.categorias.length ? d.categorias.map((c) => { const chave = c.categoria ?? ""; const corte = cortes[chave] ?? 0; return <View key={chave} style={{ gap: 4 }}><Linha titulo={nomeCategoria(c.categoria, catalogo)} valor={p.oculto ? undefined : c.valor} /><View style={{ flexDirection: ampliado ? "column" : "row", flexWrap: "wrap", gap: 8, justifyContent: "space-between" }}><Acao rotulo="Reduzir corte" icone="Minus" desativado={corte === 0} onPress={() => setCortes((s) => ({ ...s, [chave]: Math.max(0, corte - 10) }))} /><Texto variante="rotulo" style={{ alignSelf: "center" }}>{corte}%</Texto><Acao rotulo="Aumentar corte" icone="Plus" desativado={corte === 100} onPress={() => setCortes((s) => ({ ...s, [chave]: Math.min(100, corte + 10) }))} /></View></View>; }) : <Vazio texto="Registre gastos para simular cortes por categoria." />}<Texto variante="legenda" tom="inkMuted">Economia potencial</Texto><Valor valor={somarCentavos(economias)} destaque /><Texto variante="legenda" tom="inkMuted">Hipótese reversível. Não altera registros nem a previsão de compromissos conhecidos.</Texto><Acao rotulo="Zerar simulação" onPress={() => setCortes({})} /><Avisos motivos={d.motivos} /></View>; }}</RecursoDados>;
}
