import { useNavegacaoPainel } from "./navegacao";
import { useState } from "react";
import { Pressable, View } from "react-native";
import Slider from "@react-native-community/slider";
import { useTema } from "@/ui/tema";
import { Icone } from "@/ui/componentes/Icone";
import { TextoPainel as Texto, useTipografiaPainel } from "./tipografia";
import { dataPtBr, nomeCategoria } from "./catalogo";
import { usePainel } from "./provider";
import { RecursoDados, Anel, Linha, Avisos, Acao, Vazio, Valor, CORES_CATEGORIA, SeteDias } from "./base";
import { somarCentavos, percentualEmCentavos } from "./decimal";
// Barra da cor da fatia no donut, logo abaixo do nome (linha + barra = 44pt). Decorativa: o valor já está na linha.
export function Categorias() { const { navegar } = useNavegacaoPainel(); const p = usePainel(); const { cores } = useTema(); const catalogo = p.dados.categorias?.fase === "pronto" ? p.dados.categorias.dado.categorias : undefined; return <RecursoDados nome="detalhes">{(d) => <View style={{ gap: 8 }}>{!d.categorias.length ? <Vazio texto="Nenhum gasto em reais registrado neste período." /> : <><View style={{ flexDirection: "row", gap: 20, alignItems: "center" }}><Anel partes={d.categorias.map((c) => c.valor)} /><View style={{ flex: 1, gap: 4 }}><Texto variante="legenda" tom="inkMuted">Gastos em reais</Texto><Valor valor={somarCentavos(d.categorias.map((c) => c.valor))} /></View></View><View>{d.categorias.map((c, i) => <Linha key={c.categoria ?? i} titulo={nomeCategoria(c.categoria, catalogo)} valor={c.valor} onPress={() => navegar({ pathname: "/extrato", params: { categoria: c.categoria ?? "" } })}>{!p.oculto && <View accessibilityElementsHidden importantForAccessibility="no" style={{ height: 6, borderRadius: 3, backgroundColor: cores.border }}><View style={{ height: 6, borderRadius: 3, width: `${Math.max(0, c.valor) / Math.max(1, somarCentavos(d.categorias.map((x) => x.valor))) * 100}%`, backgroundColor: cores[CORES_CATEGORIA[i % CORES_CATEGORIA.length]!] }} /></View>}</Linha>)}</View></>}<Avisos motivos={d.motivos} /></View>}</RecursoDados>; }
// Uma linha por dia, mais recente primeiro. Sem `accessibilityLabel` no botão: o VoiceOver lê data e valores dos filhos.
// As barras são `View` decorativa (não `ProgressBar`, que seria anunciada duas vezes por dia) e somem com valores ocultos.
export function Calendario() {
 const { navegar } = useNavegacaoPainel(); const { ampliado } = useTipografiaPainel(); const p = usePainel(); const { cores } = useTema();
 return <RecursoDados nome="detalhes">{(d) => { const dias = [...d.dias].sort((a, b) => b.dia.localeCompare(a.dia)), maximo = Math.max(1, ...dias.map((x) => Math.max(x.entrou, x.saiu))), barras = !ampliado && !p.oculto;
  // A compra parcelada conserva o dia original (db/mes_detalhes.py): dia de outro ano leva o ano, senão dois "03/10" se confundem.
  const outroAno = (dia: string) => dia.slice(0, 4) !== d.mes.slice(0, 4), largura = dias.some((x) => outroAno(x.dia)) ? 68 : 44;
  const barra = (valor: number, cor: string) => <View style={{ height: 6, borderRadius: 3, backgroundColor: cor, width: `${Math.max(0, valor) / maximo * 100}%` }} />;
  return <View style={{ gap: 8 }}>{dias.length ? <View style={{ gap: 4 }}><SeteDias itens={dias}>{(dia) => <Pressable key={dia.dia} testID={`calendario-dia-${dia.dia}`} accessibilityRole="button" onPress={() => navegar({ pathname: "/extrato", params: { dia: dia.dia } })} style={{ minHeight: 44, flexDirection: "row", alignItems: "center", gap: 12 }}><View style={{ flex: 1, minWidth: 0, flexDirection: ampliado ? "column" : "row", alignItems: ampliado ? "flex-start" : "center", gap: ampliado ? 2 : 12 }}><Texto variante="rotulo" style={ampliado ? undefined : { width: largura }}>{dataPtBr(dia.dia).slice(0, 5) + (outroAno(dia.dia) ? `/${dia.dia.slice(2, 4)}` : "")}</Texto>{barras && <View accessibilityElementsHidden importantForAccessibility="no" style={{ flex: 1, gap: 4 }}>{barra(dia.entrou, cores.positive)}{barra(dia.saiu, cores.brand)}</View>}<View style={{ alignItems: ampliado ? "flex-start" : "flex-end", flex: barras || ampliado ? undefined : 1 }}>{dia.entrou !== 0 && <Valor valor={dia.entrou} tipo="entrada" pequeno />}{dia.saiu !== 0 && <Valor valor={dia.saiu} tipo="saida" pequeno />}{!dia.entrou && !dia.saiu && <Valor valor={0} pequeno />}</View></View><Icone nome="CaretRight" tamanho={20} /></Pressable>}</SeteDias></View> : <Vazio texto="Ainda não há movimentos neste período." />}<Avisos motivos={d.motivos} /></View>; }}</RecursoDados>;
}
// Slider nativo (UISlider): ajustável no VoiceOver sem código. O valor chega como `number` qualquer e
// `percentualEmCentavos` lança com percentual não inteiro, daí o arredondamento ao passo antes do estado.
export function Simulador() {
 const { ampliado } = useTipografiaPainel(); const { cores } = useTema();
 const p = usePainel(); const catalogo = p.dados.categorias?.fase === "pronto" ? p.dados.categorias.dado.categorias : undefined; const [cortes, setCortes] = useState<Record<string, number>>({});
 return <RecursoDados nome="detalhes">{(d) => { const economias = d.categorias.map((c) => percentualEmCentavos(c.valor, cortes[c.categoria ?? ""] ?? 0)); return <View style={{ gap: 8 }}>{d.categorias.length ? d.categorias.map((c, i) => { const chave = c.categoria ?? "", corte = cortes[chave] ?? 0, nome = nomeCategoria(c.categoria, catalogo); return <View key={chave}><View style={{ flexDirection: "row", flexWrap: ampliado ? "wrap" : "nowrap", justifyContent: "space-between", alignItems: "center", columnGap: 8 }}><Texto variante="rotulo" numberOfLines={ampliado ? undefined : 1} style={{ flexShrink: 1 }}>{nome}</Texto><View style={{ flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 0 }}><Texto variante="rotulo" tom="inkMuted">{corte}%</Texto><Texto variante="rotulo" tom="inkMuted">·</Texto><Valor valor={economias[i]!} pequeno /></View></View><Slider accessibilityLabel={`Corte em ${nome}`} style={{ height: 40 }} minimumValue={0} maximumValue={100} step={10} value={corte} minimumTrackTintColor={cores[CORES_CATEGORIA[i % CORES_CATEGORIA.length]!]} maximumTrackTintColor={cores.border} onValueChange={(v) => setCortes((s) => ({ ...s, [chave]: Math.round(v / 10) * 10 }))} /></View>; }) : <Vazio texto="Sem gastos neste mês." />}<Texto variante="legenda" tom="inkMuted">Economia potencial</Texto><Valor valor={somarCentavos(economias)} destaque /><Acao rotulo="Zerar simulação" onPress={() => setCortes({})} /><Avisos motivos={d.motivos} /></View>; }}</RecursoDados>;
}
