import { View } from "react-native";
import { TextoPainel as Texto } from "./tipografia";
import { ProgressBar } from "@/ui/componentes/ProgressBar";
import { dataPtBr, indicadorMeta } from "./catalogo";
import { usePainel } from "./provider";
import { RecursoDados, Valor, Linha, Curva, Anel, Avisos, Vazio } from "./base";
export function Metas() { const p = usePainel(); return <RecursoDados nome="metas">{(d) => <View style={{ gap: 16 }}>{!d.goals.length && <Vazio texto="Suas metas e caixinhas aparecerão aqui quando estiverem cadastradas." />}{d.goals.map((m) => <View key={m.id} style={{ gap: 8 }}><Linha titulo={m.name} valor={m.balance} detalhe={m.source === "open_finance" ? m.of_plan_active ? "Caixinha do banco" : "Caixinha do banco com sincronização indisponível" : "Caixinha manual"} />{m.is_goal ? <><Linha titulo="Objetivo" valor={m.target_amount} detalhe={m.target_date ? dataPtBr(m.target_date) : "Sem prazo definido"} />{!p.oculto && m.pct_complete !== null && <ProgressBar valor={m.pct_complete / 100} />}<Linha titulo="Ritmo mensal atual" valor={m.monthly_pace_current} /><Linha titulo="Ritmo mensal necessário" valor={m.monthly_pace_needed} /><Texto variante="legenda" tom="inkMuted">{indicadorMeta(m.indicator)}</Texto></> : <Texto variante="legenda" tom="inkMuted">Caixinha sem meta definida.</Texto>}</View>)}</View>}</RecursoDados>; }
export function Patrimonio() { return <RecursoDados nome="patrimonio">{(d) => <View style={{ gap: 12 }}><Valor valor={d.total} destaque />{d.historico.length ? <><Curva valores={d.historico.map((h) => h.total)} /><Texto variante="legenda" tom="inkMuted">Histórico desde {dataPtBr(d.historico_desde ?? d.historico[0]!.dia)}</Texto>{d.historico.map((h) => <View key={h.dia} style={{ gap: 4 }}><Linha titulo={dataPtBr(h.dia)} valor={h.total} /><Avisos motivos={h.motivos} /></View>)}</> : <Vazio texto="Ainda não há fotos anteriores do patrimônio." />}<Avisos motivos={d.motivos} /></View>}</RecursoDados>; }
const LABELS = { carteira: "Carteira", bancos: "Contas bancárias", investimentos_banco: "Investimentos do banco", caixinhas: "Caixinhas", investimentos_manuais: "Investimentos manuais" };
export function Distribuicao() { return <RecursoDados nome="patrimonio">{(d) => <View style={{ gap: 12 }}><Anel partes={Object.values(d.partes)} />{(Object.keys(d.partes) as (keyof typeof LABELS)[]).map((k) => <Linha key={k} titulo={LABELS[k]} valor={d.partes[k]} />)}<Avisos motivos={d.motivos} /></View>}</RecursoDados>; }
export function Rendimento() { const p = usePainel(); return <RecursoDados nome="rendimento">{(d) => <View style={{ gap: 10 }}><Texto variante="legenda" tom="inkMuted">Taxas contratadas informadas pelo banco. Não representam rendimento recebido.</Texto>{!d.itens.length && <Vazio texto="Seu banco ainda não informou a taxa contratada." />}{d.itens.map((r, i) => <View key={i} style={{ gap: 4 }}><Linha titulo={r.nome ?? "Investimento"} detalhe={r.instituicao ?? undefined} /><Texto variante="secao">{p.oculto ? "Taxa oculta" : r.taxa === null ? "Taxa não informada" : `${r.taxa} ${r.tipo_taxa ?? "(unidade não informada)"}`}</Texto>{r.observado_em && <Texto variante="legenda" tom="inkMuted">Informado em {new Date(r.observado_em).toLocaleDateString("pt-BR")}</Texto>}<Avisos motivos={r.motivos} /></View>)}<Avisos motivos={d.motivos} /></View>}</RecursoDados>; }
